config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :events

      resources :nonprofits

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "nonprofits#index"
  resources :events
  resources :nonprofits
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  # Direct associations

  belongs_to :nonprofit

  # Indirect associations

  has_one    :owner_user,
             through: :nonprofit,
             source: :owner_user

  # Validations

  validates :confirmed, presence: true

  validates :nonprofit_id, presence: true

  # Scopes

  def to_s
    nonprofit.to_s
  end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::V1::GraphitiController
  def index
    events = EventResource.all(params)
    respond_with(events)
  end

  def show
    event = EventResource.find(params)
    respond_with(event)
  end

  def create
    event = EventResource.build(params)

    if event.save
      render jsonapi: event, status: :created
    else
      render jsonapi_errors: event
    end
  end

  def update
    event = EventResource.find(params)

    if event.update_attributes
      render jsonapi: event
    else
      render jsonapi_errors: event
    end
  end

  def destroy
    event = EventResource.find(params)

    if event.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: event
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  def index
    @q = Event.ransack(params[:q])
    @events = @q.result(distinct: true).includes(:nonprofit,
                                                 :owner_user).page(params[:page]).per(10)
  end

  def show; end

  def new
    @event = Event.new
  end

  def edit; end

  def create
    @event = Event.new(event_params)

    if @event.save
      message = "Event was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @event, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Event was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    message = "Event was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to events_url, notice: message
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:nonprofit_id, :event_date,
                                  :event_description, :confirmed, :number_volunteers, :event_time_range, :event_lead)
  end
end

app/views/events/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Event #<%= event.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Nonprofit</dt>
      <dd>
        <% if @event.nonprofit.present? %>
          <%= link_to event.nonprofit, event.nonprofit %>
        <% end %>
      </dd>

      <dt>Event date</dt>
      <dd><%= event.event_date %></dd>

      <dt>Event description</dt>
      <dd><%= event.event_description %></dd>

      <dt>Confirmed</dt>
      <dd><%= event.confirmed %></dd>

      <dt>Number volunteers</dt>
      <dd><%= event.number_volunteers %></dd>

      <dt>Event time range</dt>
      <dd><%= event.event_time_range %></dd>

      <dt>Event lead</dt>
      <dd><%= event.event_lead %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back event, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_event_url(event), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to event, method: :delete, data: { confirm: "Do you really want to delete this event?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(event.updated_at) %> ago
  </div>
</div>

app/views/events/_event_owner_user.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Owner User
  </div>

  <ul class="list-group list-group-flush">
    <% @event.owner_user.each do |user| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/users/<%= user.id %>">
          <%= user %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/events/_events_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "events_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :event_lead_cont, "Event lead contains" %>
    <%= f.text_field :event_lead_cont, :class => "form-control", :placeholder => "Event lead contains" %>
  </div>

  <div class="form-group">
    <%= f.label :event_time_range_cont, "Event time range contains" %>
    <%= f.text_field :event_time_range_cont, :class => "form-control", :placeholder => "Event time range contains" %>
  </div>

  <div class="form-group">
    <%= f.label :number_volunteers, "Number volunteers" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :number_volunteers_gteq, :class => "form-control", :placeholder => "Number volunteers greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :number_volunteers_lteq, :class => "form-control", :placeholder => "Number volunteers less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :confirmed_eq, "Confirmed" %>
    <div>
      <label class="radio-inline">
        <%= f.radio_button :confirmed_eq, "1", checked: ((params[:q] && params[:q][:confirmed_eq]) == "1" ? "checked" : "") %> Yes
      </label>
      <label class="radio-inline">
        <%= f.radio_button :confirmed_eq, "0", checked: ((params[:q] && params[:q][:confirmed_eq]) == "0" ? "checked" : "")%> No
      </label>
      <label class="radio-inline">
        <%= f.radio_button :confirmed_eq, ""%> Either
      </label>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :event_description_cont, "Event description contains" %>
    <%= f.text_field :event_description_cont, :class => "form-control", :placeholder => "Event description contains" %>
  </div>

  <div class="form-group">
    <%= f.label :event_date, "Event date" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='event_dategteqPicker' data-target-input="nearest">
          <%= f.text_field :event_date_gteq, :class => "form-control datetimepicker-input", :placeholder => "Event date greater than or equal to", :data => {:target => '#event_dategteqPicker'} %>
          <div class="input-group-append" data-target='#event_dategteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='event_datelteqPicker' data-target-input="nearest">
          <%= f.text_field :event_date_lteq, :class => "form-control datetimepicker-input", :placeholder => "Event date less than or equal to", :data => {:target => '#event_datelteqPicker'} %>
          <div class="input-group-append" data-target='#event_datelteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#event_dategteqPicker').datetimepicker({
              format: 'MM/DD/YYYY'
          });
          $('#event_datelteqPicker').datetimepicker({
              useCurrent: false,
              format: 'MM/DD/YYYY'
          });
          $('#event_dategteqPicker').on("dp.change", function (e) {
              $('#event_datelteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#event_datelteqPicker').on("dp.change", function (e) {
              $('#event_dategteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :nonprofit_name_cont, "Nonprofit name contains" %>
    <%= f.text_field :nonprofit_name_cont, :class => "form-control", :placeholder => "Nonprofit name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :owner_user_email_cont, "Owner user email contains" %>
    <%= f.text_field :owner_user_email_cont, :class => "form-control", :placeholder => "Owner user email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/events" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#events_filters">
  Show filters
</a>

app/views/events/_form.html.erb
<% was_validated = event.errors.any? %>

<%= form_with(model: event, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% nonprofit_class = "form-control" %>
    <% nonprofit_was_invalid = event.errors.include?(:nonprofit) %>

    <% if was_validated %>
      <% if nonprofit_was_invalid %>
        <% nonprofit_class << " is-invalid" %>
      <% else %>
        <% nonprofit_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :nonprofit_id %>
    <%= f.collection_select :nonprofit_id, Nonprofit.all, :id, :to_s, {}, class: "form-control" %>
    <% if nonprofit_was_invalid %>
      <% event.errors.full_messages_for(:nonprofit).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% event_date_class = "form-control" %>
    <% event_date_was_invalid = event.errors.include?(:event_date) %>

    <% if was_validated %>
      <% if event_date_was_invalid %>
        <% event_date_class << " is-invalid" %>
      <% else %>
        <% event_date_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :event_date %>
    <%= f.date_select :event_date, class: event_date_class, placeholder: "Enter event date" %>
    <% if event_date_was_invalid %>
      <% event.errors.full_messages_for(:event_date).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% event_description_class = "form-control" %>
    <% event_description_was_invalid = event.errors.include?(:event_description) %>

    <% if was_validated %>
      <% if event_description_was_invalid %>
        <% event_description_class << " is-invalid" %>
      <% else %>
        <% event_description_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :event_description %>
    <%= f.text_area :event_description, class: event_description_class, placeholder: "Enter event description" %>
    <% if event_description_was_invalid %>
      <% event.errors.full_messages_for(:event_description).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-check">
    <% confirmed_class = "form-check-input" %>
    <% confirmed_was_invalid = event.errors.include?(:confirmed) %>

    <% if was_validated %>
      <% if confirmed_was_invalid %>
        <% confirmed_class << " is-invalid" %>
      <% else %>
        <% confirmed_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :confirmed, class: "form-check-label" do %>
      <%= f.check_box :confirmed, class: confirmed_class %> Confirmed
    <% end %>
    <% if confirmed_was_invalid %>
      <% event.errors.full_messages_for(:confirmed).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% number_volunteer_class = "form-control" %>
    <% number_volunteer_was_invalid = event.errors.include?(:number_volunteer) %>

    <% if was_validated %>
      <% if number_volunteer_was_invalid %>
        <% number_volunteer_class << " is-invalid" %>
      <% else %>
        <% number_volunteer_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :number_volunteers %>
    <%= f.number_field :number_volunteers, class: number_volunteer_class, placeholder: "Enter number volunteer" %>
    <% if number_volunteer_was_invalid %>
      <% event.errors.full_messages_for(:number_volunteer).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% event_time_range_class = "form-control" %>
    <% event_time_range_was_invalid = event.errors.include?(:event_time_range) %>

    <% if was_validated %>
      <% if event_time_range_was_invalid %>
        <% event_time_range_class << " is-invalid" %>
      <% else %>
        <% event_time_range_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :event_time_range %>
    <%= f.text_field :event_time_range, class: event_time_range_class, placeholder: "Enter event time range" %>
    <% if event_time_range_was_invalid %>
      <% event.errors.full_messages_for(:event_time_range).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% event_lead_class = "form-control" %>
    <% event_lead_was_invalid = event.errors.include?(:event_lead) %>

    <% if was_validated %>
      <% if event_lead_was_invalid %>
        <% event_lead_class << " is-invalid" %>
      <% else %>
        <% event_lead_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :event_lead %>
    <%= f.text_field :event_lead, class: event_lead_class, placeholder: "Enter event lead" %>
    <% if event_lead_was_invalid %>
      <% event.errors.full_messages_for(:event_lead).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/events/_list_item.html.erb
<%= link_to event, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= event %>
    <small class="text-muted">
      <%= time_ago_in_words(event.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/events/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Event #<%= @event.id %>
      </h2>

      <div class="card-body">
        <%= render "form", event: @event %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Events

      <%= link_to new_event_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "events/events_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Events

        <%= link_to new_event_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @events, partial: "list_item", as: :event %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @events, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Event
      </h2>

      <div class="card-body">
        <%= render "form", event: @event %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @event, partial: "card", as: :event %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "events/event_owner_user" %>
  </div>
</div>