config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :events

      resources :nonprofits

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "nonprofits#index"
  resources :events
  resources :nonprofits
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/nonprofit.rb
class Nonprofit < ApplicationRecord
  # Direct associations

  has_many   :events,
             dependent: :destroy

  belongs_to :owner_user,
             class_name: "User"

  # Indirect associations

  # Validations

  validates :contact_email, presence: true

  validates :name, presence: true

  validates :owner_user_id, presence: true

  validates :status, presence: true

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/nonprofits_controller.rb
class Api::V1::NonprofitsController < Api::V1::GraphitiController
  def index
    nonprofits = NonprofitResource.all(params)
    respond_with(nonprofits)
  end

  def show
    nonprofit = NonprofitResource.find(params)
    respond_with(nonprofit)
  end

  def create
    nonprofit = NonprofitResource.build(params)

    if nonprofit.save
      render jsonapi: nonprofit, status: :created
    else
      render jsonapi_errors: nonprofit
    end
  end

  def update
    nonprofit = NonprofitResource.find(params)

    if nonprofit.update_attributes
      render jsonapi: nonprofit
    else
      render jsonapi_errors: nonprofit
    end
  end

  def destroy
    nonprofit = NonprofitResource.find(params)

    if nonprofit.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: nonprofit
    end
  end
end

app/controllers/nonprofits_controller.rb
class NonprofitsController < ApplicationController
  before_action :current_user_must_be_nonprofit_owner_user,
                only: %i[edit update destroy]

  before_action :set_nonprofit, only: %i[show edit update destroy]

  def index
    @q = Nonprofit.ransack(params[:q])
    @nonprofits = @q.result(distinct: true).includes(:owner_user,
                                                     :events).page(params[:page]).per(10)
  end

  def show
    @event = Event.new
  end

  def new
    @nonprofit = Nonprofit.new
  end

  def edit; end

  def create
    @nonprofit = Nonprofit.new(nonprofit_params)

    if @nonprofit.save
      message = "Nonprofit was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @nonprofit, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @nonprofit.update(nonprofit_params)
      redirect_to @nonprofit, notice: "Nonprofit was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @nonprofit.destroy
    message = "Nonprofit was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to nonprofits_url, notice: message
    end
  end

  private

  def current_user_must_be_nonprofit_owner_user
    set_nonprofit
    unless current_user == @nonprofit.owner_user
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def set_nonprofit
    @nonprofit = Nonprofit.find(params[:id])
  end

  def nonprofit_params
    params.require(:nonprofit).permit(:name, :category, :mission,
                                      :contact_name, :contact_email, :contact_phone, :owner_user_id, :status, :notes)
  end
end

app/views/nonprofits/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Nonprofit #<%= nonprofit.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= nonprofit.name %></dd>

      <dt>Category</dt>
      <dd><%= nonprofit.category %></dd>

      <dt>Mission</dt>
      <dd><%= nonprofit.mission %></dd>

      <dt>Contact name</dt>
      <dd><%= nonprofit.contact_name %></dd>

      <dt>Contact email</dt>
      <dd><%= nonprofit.contact_email %></dd>

      <dt>Contact phone</dt>
      <dd><%= nonprofit.contact_phone %></dd>

      <dt>Owner user</dt>
      <dd>
        <% if @nonprofit.owner_user.present? %>
          <%= link_to nonprofit.owner_user, nonprofit.owner_user %>
        <% end %>
      </dd>

      <dt>Status</dt>
      <dd><%= nonprofit.status %></dd>

      <dt>Notes</dt>
      <dd><%= nonprofit.notes %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back nonprofit, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @nonprofit.owner_user %>
          <%= link_to edit_nonprofit_url(nonprofit), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @nonprofit.owner_user %>
          <%= link_to nonprofit, method: :delete, data: { confirm: "Do you really want to delete this nonprofit?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(nonprofit.updated_at) %> ago
  </div>
</div>

app/views/nonprofits/_form.html.erb
<% was_validated = nonprofit.errors.any? %>

<%= form_with(model: nonprofit, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = nonprofit.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% nonprofit.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% category_class = "form-control" %>
    <% category_was_invalid = nonprofit.errors.include?(:category) %>

    <% if was_validated %>
      <% if category_was_invalid %>
        <% category_class << " is-invalid" %>
      <% else %>
        <% category_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :category %>
    <%= f.text_field :category, class: category_class, placeholder: "Enter category" %>
    <% if category_was_invalid %>
      <% nonprofit.errors.full_messages_for(:category).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% mission_class = "form-control" %>
    <% mission_was_invalid = nonprofit.errors.include?(:mission) %>

    <% if was_validated %>
      <% if mission_was_invalid %>
        <% mission_class << " is-invalid" %>
      <% else %>
        <% mission_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :mission %>
    <%= f.text_area :mission, class: mission_class, placeholder: "Enter mission" %>
    <% if mission_was_invalid %>
      <% nonprofit.errors.full_messages_for(:mission).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% contact_name_class = "form-control" %>
    <% contact_name_was_invalid = nonprofit.errors.include?(:contact_name) %>

    <% if was_validated %>
      <% if contact_name_was_invalid %>
        <% contact_name_class << " is-invalid" %>
      <% else %>
        <% contact_name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :contact_name %>
    <%= f.text_field :contact_name, class: contact_name_class, placeholder: "Enter contact name" %>
    <% if contact_name_was_invalid %>
      <% nonprofit.errors.full_messages_for(:contact_name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% contact_email_class = "form-control" %>
    <% contact_email_was_invalid = nonprofit.errors.include?(:contact_email) %>

    <% if was_validated %>
      <% if contact_email_was_invalid %>
        <% contact_email_class << " is-invalid" %>
      <% else %>
        <% contact_email_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: contact_email_class, placeholder: "Enter contact email" %>
    <% if contact_email_was_invalid %>
      <% nonprofit.errors.full_messages_for(:contact_email).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% contact_phone_class = "form-control" %>
    <% contact_phone_was_invalid = nonprofit.errors.include?(:contact_phone) %>

    <% if was_validated %>
      <% if contact_phone_was_invalid %>
        <% contact_phone_class << " is-invalid" %>
      <% else %>
        <% contact_phone_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :contact_phone %>
    <%= f.text_field :contact_phone, class: contact_phone_class, placeholder: "Enter contact phone" %>
    <% if contact_phone_was_invalid %>
      <% nonprofit.errors.full_messages_for(:contact_phone).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.hidden_field :owner_user_id, value: current_user.id %>
  <div class="form-group">
    <% status_class = "form-control" %>
    <% status_was_invalid = nonprofit.errors.include?(:status) %>

    <% if was_validated %>
      <% if status_was_invalid %>
        <% status_class << " is-invalid" %>
      <% else %>
        <% status_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :status %>
    <%= f.text_area :status, class: status_class, placeholder: "Enter status" %>
    <% if status_was_invalid %>
      <% nonprofit.errors.full_messages_for(:status).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% note_class = "form-control" %>
    <% note_was_invalid = nonprofit.errors.include?(:note) %>

    <% if was_validated %>
      <% if note_was_invalid %>
        <% note_class << " is-invalid" %>
      <% else %>
        <% note_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :notes %>
    <%= f.text_area :notes, class: note_class, placeholder: "Enter note" %>
    <% if note_was_invalid %>
      <% nonprofit.errors.full_messages_for(:note).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/nonprofits/_list_item.html.erb
<%= link_to nonprofit, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= nonprofit %>
    <small class="text-muted">
      <%= time_ago_in_words(nonprofit.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/nonprofits/_nonprofit_events.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Events

    <a data-toggle="collapse" href="#nonprofit_events_new_form">
      Add event
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @nonprofit.events.each do |event| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to event, event %>

        <%= link_to event, method: :delete, data: { confirm: "Do you really want to delete this event" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="nonprofit_events_new_form">
        <%= render partial: "nonprofits/nonprofit_events_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/nonprofits/_nonprofit_events_new_form.html.erb
<%= form_with(model: @event, local: true) do |f| %>

  <%= f.hidden_field :nonprofit_id, value: @nonprofit.id %>

  <div class="form-group">
    <%= f.label :event_date %>

    <%= f.date_select :event_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :event_description %>
    <%= f.text_area :event_description, rows: "3", class: "form-control" %>
  </div>

  <div class="form-check">
    <%= f.check_box :confirmed, class: "form-check-input" %>
    <%= f.label :confirmed, class: "form-check-label" %>
  </div>

  <div class="form-group">
    <%= f.label :number_volunteers %>

    <%= f.text_field :number_volunteers, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :event_time_range %>

    <%= f.text_field :event_time_range, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :event_lead %>

    <%= f.text_field :event_lead, class: "form-control" %>
  </div>

  <%= f.submit "Create event", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/nonprofits/_nonprofits_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "nonprofits_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :notes_cont, "Notes contains" %>
    <%= f.text_field :notes_cont, :class => "form-control", :placeholder => "Notes contains" %>
  </div>

  <div class="form-group">
    <%= f.label :status_cont, "Status contains" %>
    <%= f.text_field :status_cont, :class => "form-control", :placeholder => "Status contains" %>
  </div>

  <div class="form-group">
    <%= f.label :contact_phone_cont, "Contact phone contains" %>
    <%= f.text_field :contact_phone_cont, :class => "form-control", :placeholder => "Contact phone contains" %>
  </div>

  <div class="form-group">
    <%= f.label :contact_email_cont, "Contact email contains" %>
    <%= f.text_field :contact_email_cont, :class => "form-control", :placeholder => "Contact email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :contact_name_cont, "Contact name contains" %>
    <%= f.text_field :contact_name_cont, :class => "form-control", :placeholder => "Contact name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :mission_cont, "Mission contains" %>
    <%= f.text_field :mission_cont, :class => "form-control", :placeholder => "Mission contains" %>
  </div>

  <div class="form-group">
    <%= f.label :category_cont, "Category contains" %>
    <%= f.text_field :category_cont, :class => "form-control", :placeholder => "Category contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :owner_user_email_cont, "Owner user email contains" %>
    <%= f.text_field :owner_user_email_cont, :class => "form-control", :placeholder => "Owner user email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/nonprofits" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#nonprofits_filters">
  Show filters
</a>

app/views/nonprofits/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Nonprofit #<%= @nonprofit.id %>
      </h2>

      <div class="card-body">
        <%= render "form", nonprofit: @nonprofit %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/nonprofits/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Nonprofits

      <%= link_to new_nonprofit_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "nonprofits/nonprofits_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Nonprofits

        <%= link_to new_nonprofit_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @nonprofits, partial: "list_item", as: :nonprofit %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @nonprofits, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/nonprofits/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Nonprofit
      </h2>

      <div class="card-body">
        <%= render "form", nonprofit: @nonprofit %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/nonprofits/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @nonprofit, partial: "card", as: :nonprofit %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "nonprofits/nonprofit_events" %>
  </div>
</div>